package server

import "net/http"

func (s *Server) registerRoutes() {
	// Static files
	s.mux.Handle("/static/", http.StripPrefix("/static/", http.FileServer(s.staticFS)))

	// Pages
	s.mux.HandleFunc("/", s.handleIndex)
	s.mux.HandleFunc("/datasources", s.handleDatasources)
	s.mux.HandleFunc("/variables", s.handleVariables)
	s.mux.HandleFunc("/palettes", s.handlePalettes)
	s.mux.HandleFunc("/references", s.handleReferences)
	s.mux.HandleFunc("/editor", s.handleEditor)
	s.mux.HandleFunc("/metrics", s.handleMetrics)
	s.mux.HandleFunc("/preview", s.handlePreview)
	s.mux.HandleFunc("/profiles", s.handleProfiles)
	s.mux.HandleFunc("/settings", s.handleSettings)
	s.mux.HandleFunc("/templates", s.handleTemplatesPage)
	s.mux.HandleFunc("/compare", s.handleComparePage)
	s.mux.HandleFunc("/panel-builder", s.handlePanelBuilderPage)
	s.mux.HandleFunc("/import", s.handleImportPage)

	// API endpoints (HTMX)
	s.mux.HandleFunc("/api/push", s.handlePush)
	s.mux.HandleFunc("/api/generate", s.handleGenerate)
	s.mux.HandleFunc("/api/datasource/test", s.handleDatasourceTest)
	s.mux.HandleFunc("/api/datasource/url", s.handleDatasourceURL)
	s.mux.HandleFunc("/api/datasource/add", s.handleDatasourceAdd)
	s.mux.HandleFunc("/api/datasource/delete", s.handleDatasourceDelete)
	s.mux.HandleFunc("/api/datasource/targets", s.handleDatasourceTargets)
	s.mux.HandleFunc("/api/datasource/targets/metrics", s.handleDatasourceTargetMetrics)
	s.mux.HandleFunc("/api/datasources/compare-all", s.handleDatasourcesCompareAll)
	s.mux.HandleFunc("/api/datasources/compare-labels", s.handleDatasourcesCompareLabels)
	s.mux.HandleFunc("/api/datasources/variable-snippet", s.handleVariableSnippet)
	s.mux.HandleFunc("/api/metrics/browse", s.handleMetricsBrowse)
	s.mux.HandleFunc("/api/metrics/jobs", s.handleMetricsJobs)
	s.mux.HandleFunc("/api/metrics/compare", s.handleMetricsCompare)
	s.mux.HandleFunc("/api/metrics/snippet", s.handleMetricsSnippet)
	s.mux.HandleFunc("/api/metrics/ai-suggest", s.handleAISuggest)
	s.mux.HandleFunc("/api/metrics/ai-suggest-bulk", s.handleAISuggestBulk)
	s.mux.HandleFunc("/api/metrics/comparison-snippet", s.handleComparisonSnippet)
	s.mux.HandleFunc("/api/config/reload", s.handleConfigReload)
	s.mux.HandleFunc("/api/config/save", s.handleConfigSave)
	s.mux.HandleFunc("/api/config/insert-section", s.handleInsertSection)
	s.mux.HandleFunc("/api/preview", s.handlePreviewAPI)
	s.mux.HandleFunc("/api/palette/color/set", s.handlePaletteColorSet)
	s.mux.HandleFunc("/api/palette/color/delete", s.handlePaletteColorDelete)
	s.mux.HandleFunc("/api/palette/color/rename", s.handlePaletteColorRename)
	s.mux.HandleFunc("/api/palette/create", s.handlePaletteCreate)
	s.mux.HandleFunc("/api/palette/delete", s.handlePaletteDelete)
	s.mux.HandleFunc("/api/palette/activate", s.handlePaletteActivate)
	s.mux.HandleFunc("/api/labels/discover", s.handleLabelsDiscover)
	s.mux.HandleFunc("/api/labels/values", s.handleLabelValues)
	s.mux.HandleFunc("/api/variable/add", s.handleVariableAdd)
	s.mux.HandleFunc("/api/variable/add-bulk", s.handleBulkVariableAdd)
	s.mux.HandleFunc("/api/variable/delete", s.handleVariableDelete)
	s.mux.HandleFunc("/api/template/preview", s.handleTemplatePreview)
	s.mux.HandleFunc("/api/template/create", s.handleTemplateCreate)
	s.mux.HandleFunc("/api/template/load", s.handleTemplateLoad)
	s.mux.HandleFunc("/api/template/merge", s.handleTemplateMerge)
	s.mux.HandleFunc("/api/compare/generate-dashboard", s.handleCompareGenerate)
	s.mux.HandleFunc("/api/panel/preview-yaml", s.handlePanelPreviewYAML)
	s.mux.HandleFunc("/api/config/insert-panel", s.handleInsertPanel)
	s.mux.HandleFunc("/api/preview/live", s.handleLivePreview)
	s.mux.HandleFunc("/api/import/parse", s.handleImportParse)
}
